name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          #  Note that the GITHUB_TOKEN is NOT a personal access token. A GitHub Actions runner automatically creates a
          #  GITHUB_TOKEN secret to authenticate in your workflow. So, you can start to deploy immediately without any
          #  configuration.
          # 不用管这个 secret，github action 会自动创建
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: mewoooew/mewoooew.github.io
          publish_branch: main
          publish_dir: ./public
          commit_message: ${{github.event.head_commit.message }}
